project:
  type: book
  output-dir: docs

book:
  title: "Handbook_Spatial"
  author: "Tobias Rüttenauer"
  date: "26/06/2023"
  chapters:
      - index.qmd
      - 01_chapter.qmd
      - 02_retreive_data.qmd

bibliography: references.bib

format: docx
  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true
    
output:
  word_document:

editor: visual

